# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 992afa4bbf5ffc7e3f16711eed220ce9a51ceedf9efb449e4e47c939abe123596477aa55a273f804779a33aea12f79a1789b221fadc26f3357df3c5032ffa0ff

test:
  secret_key_base: 76a3713a9c0e88b72dcbdcf57ef4a7be1dc93ff886e5a8206bb498eac568e217fc4ed80b41388ce336799709134a96784ccc393e65a5642b466fe8565933d92c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 812fe96ce477edb6e71de55dffc91f47d607ebae1009edbb4c94c2a6f08c73600560c398b7322bbc7a47b911045b7a355dcd9a5373fea2f0f3991ea25e91e2d7
